display_name: FlutterCi
publisher_display_name: FlutterCi
identity_name: FlutterCi.FlutterCiNext
msix_version: 2.3.1.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us, zh-cn, zh-tw, tr-tr,fa-ir,ru-ru,pt-br,es-es
protocol_activation: flutterci
execution_alias: flutterci
sign_msiz: "false"
# certificate_path: windows\sign.pfx
# certificate_password:
publisher: CN=8CB43675-F44B-4AA5-9372-E8727781BDC4
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart
