display_name: FlutterCi
url: https://github.com/flutterci/flutterci-next/
license: Other

packager: flutterci
packagerEmail: linux@flutterci.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/fruit_640.png

keywords:
  - FlutterCi
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: FlutterCi

group: Applications/Internet

startup_notify: true
