app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: FlutterCi
publisher_url: https://github.com/jeffid/flutter_ci
display_name: FlutterCi
executable_name: FlutterCi.exe
output_base_file_name: FlutterCi.exe
create_desktop_icon: true
# install_dir_name: "{autopf64}\\FlutterCi"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - en
  - zh
script_template: inno_setup.sas
