name: Flutter CI

# 创建触发打包条件：只要推送tag，就会触发版本打包

on:
  push:
    tags:
      - v*
    
jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android-apk
            os: ubuntu-latest
            targets: apk

          - platform: android-aab
            os: ubuntu-latest
            targets: aab

          # - platform: windows
          #   os: windows-2019
          #   aarch: amd64
          #   targets: exe,msix

          # - platform: linux
          #   os: ubuntu-22.04
          #   aarch: amd64
          #   targets: AppImage,deb,rpm

          # - platform: macos
          #   os: macos-13
          #   aarch: universal
          #   targets: dmg,pkg
            
          # - platform: ios
          #   os: macos-14
          #   aarch: universal
          #   filename: fci-ios
          #   targets: ipa

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Setup Java
        if: startsWith(matrix.platform,'android')
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # - name: Setup NDK
      #   if: startsWith(matrix.platform,'android')
      #   uses: nttld/setup-ndk@v1
      #   id: setup-ndk
      #   with:
      #     ndk-version: ${{ env.NDK_VERSION }}
      #     add-to-path: true
      #     link-to-sdk: true

      # - name: Setup Gradle 8.1
      #   if: startsWith(matrix.platform,'android')
      #   uses: gradle/actions/setup-gradle@v3
      #   with:
      #     gradle-version: 7.5
      # - name: Setup dependencies
      #   run: |
      #     make ${{ matrix.platform }}-install-dependencies

      
      # Get flutter dependencies.
      - run: flutter pub get    
      # Build apk
      # - run: flutter build apk --target-platform android-arm
      - run: flutter build apk --release --target-platform=android-arm64 --no-shrink
      # - name: Upload APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: apk
      #     path: build/app/outputs/apk/release/app-release.apk
      # 发包
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

    

